# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ARM_SERVICE_CONNECTION: "azure-terraform-conn"

stages:
- stage: TerraformInitPlan
  jobs:
  - job: InitPlan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(ARM_SERVICE_CONNECTION)
        backendAzureRmResourceGroupName: 'tfstate-rg'
        backendAzureRmStorageAccountName: 'tfstatekp2026dev123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: $(ARM_SERVICE_CONNECTION)

- stage: TerraformApply
  dependsOn: TerraformInitPlan
  condition: succeeded()
  jobs:
  - deployment: Apply
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: $(ARM_SERVICE_CONNECTION)
              args: '-auto-approve'